INSERT INTO rtp."Payment_Method" (code, name) VALUES('TIMOPA0001', 'CASH')
INSERT INTO rtp."Payment_Method" (code, name) VALUES('TIMOPA0003', 'CREDIT_CARD')
INSERT INTO rtp."Payment_Method" (code, name) VALUES('TIMOPA0024', 'DEBIT_CARD')
INSERT INTO rtp."Payment_Method" (code, name) VALUES('TIMOPA0026', 'PREPAID_CARD')

INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080001', 'ATM', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080002', 'PHONE', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080004', 'OTC', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080008', 'INTERNET', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080009', 'MOBILE', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080012', 'ODC', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080015', 'AUTOMATED PAYMENT MACHINE(INSIDE MERALCO)', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080016', 'AUTOMATED PAYMENT MACHINE(OUTSIDE MERALCO)', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080017', 'OTC - BAYAD CENTER PARTNERS', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080018', 'INSIDE MERALCO BUS CTR', 'BAYAD CENTER')
INSERT INTO rtp."Channel" (channel, name, payment_collector) VALUES('080019', 'DIGITAL - BAYAD CENTER PARTNERS', 'BAYAD CENTER')